Added installation of MSVC Build Tools to workflow for Windows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,34 +38,37 @@ jobs:
       run: |
         brew install openssl gtk+
 
-    - name: Install OpenSSL on Windows
+    - name: Set OpenSSL environment variables on macOS
+      if: matrix.os == 'macos-latest'
+      run: |
+        OPENSSL_PREFIX=$(brew --prefix openssl)
+        if [ -d "$OPENSSL_PREFIX" ]; then
+          echo "OPENSSL_DIR=$OPENSSL_PREFIX" >> $GITHUB_ENV
+          echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX/include" >> $GITHUB_ENV
+          echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX/lib" >> $GITHUB_ENV
+        else
+          echo "Error: OpenSSL prefix not found."
+          exit 1
+        fi
+
+    - name: Install MSVC Build Tools and OpenSSL on Windows
       if: matrix.os == 'windows-latest'
       run: |
+        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
         choco install openssl
 
     - name: Set OpenSSL environment variables on Windows
       if: matrix.os == 'windows-latest'
       run: |
-        if (Test-Path "C:\Program Files\OpenSSL") {
-          echo "OPENSSL_DIR=C:\Program Files\OpenSSL" >> $GITHUB_ENV
-          echo "OPENSSL_INCLUDE_DIR=C:\Program Files\OpenSSL\include" >> $GITHUB_ENV
-          echo "OPENSSL_LIB_DIR=C:\Program Files\OpenSSL\lib" >> $GITHUB_ENV
-        } elseif (Test-Path "C:\OpenSSL-Win64") {
-          echo "OPENSSL_DIR=C:\OpenSSL-Win64" >> $GITHUB_ENV
-          echo "OPENSSL_INCLUDE_DIR=C:\OpenSSL-Win64\include" >> $GITHUB_ENV
-          echo "OPENSSL_LIB_DIR=C:\OpenSSL-Win64\lib" >> $GITHUB_ENV
-        } else {
-          echo "Error: OpenSSL directory not found."
+        OPENSSL_PREFIX="C:\\Program Files\\OpenSSL"
+        if [ -d "$OPENSSL_PREFIX" ]; then
+          echo "OPENSSL_DIR=$OPENSSL_PREFIX" >> $GITHUB_ENV
+          echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX\\include" >> $GITHUB_ENV
+          echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX\\lib" >> $GITHUB_ENV
+        else
+          echo "Error: OpenSSL prefix not found."
           exit 1
-        }
-
-    - name: Set OpenSSL environment variables on macOS
-      if: matrix.os == 'macos-latest'
-      run: |
-        OPENSSL_PREFIX=$(brew --prefix openssl)
-        echo "OPENSSL_DIR=$OPENSSL_PREFIX" >> $GITHUB_ENV
-        echo "OPENSSL_INCLUDE_DIR=$OPENSSL_PREFIX/include" >> $GITHUB_ENV
-        echo "OPENSSL_LIB_DIR=$OPENSSL_PREFIX/lib" >> $GITHUB_ENV
+        fi
 
     - name: Install dependencies
       run: pnpm install
